// ACTION TYPES
const FETCH_ENROLLED_COURSES = "FETCH_ENROLLED_COURSES";
const FETCH_ALL_COURSES = "FETCH_ALL_COURSES";
const FETCH_STUDENT = "FETCH_STUDENT";
const ADD_COURSE = "ADD_COURSE";
const DROP_COURSE = "DROP_COURSE";
const SWAP_COURSE = "SWAP_COURSE";
const FETCH_PROFESSOR_REVIEWS = "FETCH_PROFESSOR_REVIEWS";

export default {
  FETCH_ENROLLED_COURSES,
  FETCH_ALL_COURSES,
  FETCH_STUDENT,
  ADD_COURSE,
  DROP_COURSE,
  SWAP_COURSE,
  FETCH_PROFESSOR_REVIEWS,
};
