// Action types for enrollment
const FETCH_ENROLLED_COURSES = "FETCH_ENROLLED_COURSES";
const FETCH_ALL_COURSES = "FETCH_ALL_COURSES";
const FETCH_STUDENT = "FETCH_STUDENT";
const ADD_COURSE = "ADD_COURSE";

export default {
  FETCH_ENROLLED_COURSES,
  FETCH_ALL_COURSES,
  FETCH_STUDENT,
  ADD_COURSE,
};
